update

diff --git a/delmail b/delmail
--- a/delmail
+++ b/delmail
@@ -1,23 +1,37 @@
 #!/bin/bash
-# $Id: delmail,v 1.1 2015/05/20 15:44:38 fulford Exp $
+# $Id: delmail,v 1.2 2015/05/20 17:23:37 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/delmail,v $
-# $Revision: 1.1 $
+# $Revision: 1.2 $
 # Author C W Fulford.
 # Copyright 2014-2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0709 229 5385
 ########################################################################
 cmd=`basename $0`
+[ $cmd == "delmail" ] && expunge=":"
 tmp=/var/tmp/$cmd.$$
-syntax="$cmd [-a <addr>] [-c <config>] [-d] [-i <imap_server>] [-f] [-i <imap_srvr> [-L] [-l] [-m <mail_box>] [-n] [-P <password>] [-p <port> [-u <username>] [-v] [-w <#>] [-x] [<config_id>]|[-V]"
+case $cmd in
+	chkmail) syntax="$cmd [-a <addr>] [-c <config>] [-d] [-i <imap_server>] [-L] [-l] [-m <mail_box>] [-n] [-P <password>] [-p <port> [-u <username>] [-v] [-w <#>] [<config_id>]|[-V]";;
+	delmail) syntax="$cmd [-c <config>] [-d] [-i <imap_server>] [-l] [-m <mbox>] [-n] [-P <password>] [-p <port> [-v] [-w <#>] <mail_address>|[-V]";;
 while [ $# -gt 0 ] ;do
 	case $1 in 
-		-a) echo "addr=$2">>$tmp;shift 2;;
+		-a) [ $cmd = "delmail" ]&&{
+			echo $syntax>&2;
+			exit 1
+		    }
+		    echo "addr=$2">>$tmp;shift 2;;
 		-c) config=$2;shift;;
 		-d) debug=:;set -x;shift;;
-		-f) chk_fldr=:;shift;;
+		-f) [ $cmd = "delmail" ]{
+			echo $syntax>&2;
+			exit 1
+		    chk_fldr=:;shift;; }
 		-i) echo "srvr=$2">$tmp;shift 2;;
-		-L) list=:;shift;;				
+		-L) [ $cmd = "delmail" ]&&{
+			echo $syntax>&2;
+			exit 1
+		    }
+		    list=":";shift;;
 		-l) log=:;shift;;				
 		-m) echo "mbox=$2">>$tmp;shift 2;;
 		-n) notice=:;shift;;
@@ -25,18 +39,18 @@ while [ $# -gt 0 ] ;do
 		-p) port=$2>>$tmp;shift 2;;
 		-u) echo "user=$2">>$tmp;shift 2;;
 		-v) verbose=:;nl="\\n";shift;;
-		-V) echo "$cmd $Revision: 1.1 $ $Date: 2015/05/20 15:44:38 $"|awk '{print $1,$3,$6}';exit;;  
+		-V) echo "$cmd $Revision: 1.2 $ $Date: 2015/05/20 17:23:37 $"|awk '{print $1,$3,$6}';exit;;  
 		-w) echo "warn=$2">>$tmp;shift 2;;
-		-x) expunge=:;shift;;
 		-*) echo "syntax: $syntax">&2;exit 1;;
 	         *) id=$1;shift;;
 	esac
 done
+
 config=${config:="/usr/local/etc/chkmail.cf"}
 cnt_msgs=/usr/local/etc/msg_cnt
 lst_mbxs=/usr/local/etc/lst_mbxs
 del_msgs=/usr/local/etc/msg_del
-
+set
 [ -r "$config" -a -n "$id" ] &&  {
 	if grep "$id:">/dev/null $config;then
 		eval `sed -ne '/^'$id':/,/^$/{/^[ 	][^#]/p}' $config`
@@ -89,7 +103,18 @@ nc -zw 2 $srvr $port </dev/null || {
        	echo -e "${nl}Port $port unavailable on $srvr ($user).">&2
 	exit 1
 }
-
+for n in "$folders" ;do
+	echo $folders|egrep -wq '.Archive' && archives=:
+done
+		
+if [ "$archives" ];then
+	ay=2012
+	while  [ $ay -lt  `date "+%Y"` ];do
+		afolders="$afolders INBOX.Archive.$ay"
+	       	ay=`expr $ay + 1`
+	done	
+	folders=`echo $folders|sed -e "s/\.Archive/$afolders/"` 
+fi
 for m in $mbox $folders ;do
   	[ "$verbose" ] && echo -n "$cmd: Checking ${user}'s $m on $srvr: "
 	if [ $port -eq 22 ];then
@@ -97,7 +122,7 @@ for m in $mbox $folders ;do
 		vuser=`echo $addr|awk -F@ '{print $1}'`
 		f=`echo $m|awk '{sub(/INBOX/,"");print}'`	
 		mdir=/var/qmail/mailnames/$mdomain/$vuser/Maildir/$f
-		total=`ssh $srvr "sudo find $mdir/{cur,new} -type f"|wc -l`
+		total=`ssh $srvr "sudo find $mdir/{cur,new} -type f" 2>/dev/null|wc -l`
 	else
   		suser=`echo $user|sed -ne 's/^\(.*\)@.*/\1/p'`
 		total=`expect -f $cnt_msgs $srvr $proto  $addr $m "$passwd"|\
@@ -111,7 +136,7 @@ for m in $mbox $folders ;do
 			echo  "Warning: ${user}'s $m on $srvr has $total messages" >&2
 		fi
 	       	[ "$log" ] && {
-		  	logger -p mail.notice -t $cmd: "$user $m on $srvr checked. $total mesgs"
+		  	logger -p mail.notice -t $cmd "$total messages for $user $m at $srvr."
 		}
 
 			
@@ -139,18 +164,21 @@ for m in $mbox $folders ;do
 		if [ "$expunge" ];then
 		   del=`expr $total - $warn`
 		   expect -f $del_msgs $srvr $proto  $addr $m "$passwd" $del
+		   total=`expr $total - $del`
 		     [ "$log" ] &&{
-		       logger -t $cmd -p mail.notice "$del messages deleted for $user $mbx at $srvr."
+		       	logger -p mail.notice -t $cmd "$del messages deleted for $user $m at $srvr."
+		  	logger -p mail.notice -t $cmd "$total messages for $user $m at $srvr."
 		      }
 		      [ $verbose ] &&{
 		      	s=s;[ $del -eq 1 ] && s=""
-		      	echo "$cmd: $del message$s deleted for $user $mbx at $srvr"
+		      	echo "$cmd: $del message$s deleted for $user $m at $srvr."
+			echo "$cmd: $total message$s remaining for $user $m at $srvr."
 		      }
 		fi
 	else
 		[ "$verbose" ] && echo "$cmd: $user $mbx not found."
 		[ "$log" ] && {
-			logger -p mail.notice -t $cmd "$user $mbx on $srvr checked. Not found!"
+			logger -p mail.notice -t $cmd "$user $m at $srvr. Not found!"
 		}
 
 	fi
