update

diff --git a/delmail b/delmail
--- a/delmail
+++ b/delmail
@@ -1,186 +1,108 @@
 #!/bin/bash
-# $Id: delmail,v 1.2 2015/05/20 17:23:37 fulford Exp fulford $
+# $Id: delmail,v 1.3 2015/05/20 17:31:13 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/delmail,v $
-# $Revision: 1.2 $
+# $Revision: 1.3 $
 # Author C W Fulford.
-# Copyright 2014-2015 (c) C W Fulford.
+# Copyright 2015 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
 # For assistance contact fulford@fulford.net 0709 229 5385
 ########################################################################
 cmd=`basename $0`
-[ $cmd == "delmail" ] && expunge=":"
-tmp=/var/tmp/$cmd.$$
-case $cmd in
-	chkmail) syntax="$cmd [-a <addr>] [-c <config>] [-d] [-i <imap_server>] [-L] [-l] [-m <mail_box>] [-n] [-P <password>] [-p <port> [-u <username>] [-v] [-w <#>] [<config_id>]|[-V]";;
-	delmail) syntax="$cmd [-c <config>] [-d] [-i <imap_server>] [-l] [-m <mbox>] [-n] [-P <password>] [-p <port> [-v] [-w <#>] <mail_address>|[-V]";;
+ver=`echo "$Id: delmail,v 1.3 2015/05/20 17:31:13 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
+syntax="$cmd [[-c <configfile>] [-d] [-i <company_id>] [-l] [-m <max>] [-v] <email_address>]|[-V]"
 while [ $# -gt 0 ] ;do
 	case $1 in 
-		-a) [ $cmd = "delmail" ]&&{
-			echo $syntax>&2;
-			exit 1
-		    }
-		    echo "addr=$2">>$tmp;shift 2;;
-		-c) config=$2;shift;;
-		-d) debug=:;set -x;shift;;
-		-f) [ $cmd = "delmail" ]{
-			echo $syntax>&2;
-			exit 1
-		    chk_fldr=:;shift;; }
-		-i) echo "srvr=$2">$tmp;shift 2;;
-		-L) [ $cmd = "delmail" ]&&{
-			echo $syntax>&2;
-			exit 1
-		    }
-		    list=":";shift;;
-		-l) log=:;shift;;				
-		-m) echo "mbox=$2">>$tmp;shift 2;;
-		-n) notice=:;shift;;
-		-P) echo "passwd=$2">>$tmp;shift 2;;
-		-p) port=$2>>$tmp;shift 2;;
-		-u) echo "user=$2">>$tmp;shift 2;;
-		-v) verbose=:;nl="\\n";shift;;
-		-V) echo "$cmd $Revision: 1.2 $ $Date: 2015/05/20 17:23:37 $"|awk '{print $1,$3,$6}';exit;;  
-		-w) echo "warn=$2">>$tmp;shift 2;;
-		-*) echo "syntax: $syntax">&2;exit 1;;
-	         *) id=$1;shift;;
+		-c) config=$2;shift 2;;
+		-d) set -x;debug=0;shift;;
+		-i) co=$2;shift 2;;
+		-l) log=:; shift;;
+		-m) clmax=$2;shift 2;;
+		-v) verbose=:;shift;;
+		-V) echo "$cmd $Revision: 1.3 $ $Date: 2015/05/20 17:31:13 $"|awk '{print $1,$3,$6}';exit;;  
+		 *@*) ma=$1;shift ;;
+	 	 *) echo "$syntax">&2; exit 1;;
 	esac
 done
 
-config=${config:="/usr/local/etc/chkmail.cf"}
-cnt_msgs=/usr/local/etc/msg_cnt
-lst_mbxs=/usr/local/etc/lst_mbxs
-del_msgs=/usr/local/etc/msg_del
-set
-[ -r "$config" -a -n "$id" ] &&  {
-	if grep "$id:">/dev/null $config;then
-		eval `sed -ne '/^'$id':/,/^$/{/^[ 	][^#]/p}' $config`
-	else
-		echo "$cmd: $id not found in $config" >&2
+
+[ "$ma" ] ||{ echo "$syntax" >&2;exit 1;}
+expr "$ma" : ".*@[^\.]*\.[^\.]*">/dev/null ||{
+	echo "$ma is not a valid e-mail address" >&2
+	exit 1
+}
+md=`echo $ma|awk -F@ '{print $2}'`
+getent hosts $md 2>&1 >/dev/null ||{
+	echo "$cmd can't find IP address for $md">&2 
+	exit 1 
+}  
+mu=`echo $ma|awk -F@ '{print $1}'`
+
+config=${config:-/usr/local/etc/${cmd}.cf}
+[ -r $config ] ||{ echo  "$cmd: Can\'t find $config"; exit 1 ;}
+eval `sed <$config -ne "/^$md:/,/^$/{/^[\t ]*[^#].*=.*/p}"`
+
+max=${max:-5000}
+max=${clmax:-$max}
+basedir=${basedir:-/var/qmail/mailnames}
+maildir=$basedir/$md/$mu/Maildir
+archf=$maildir/.Archive
+proto=${proto:-ssh}
+tmp=/tmp/$cmd$$
+
+[ "$max" -ge 0 ] >/dev/null 2>&1 ||{
+	echo "$cmd: max must be set to a positive integer" >&2
+	exit 1
+}
+[ -n "$co" ]||{
+	echo "$cmd: Warning - company id required for reporting" >&2
+}
+[ "$verbose" ] && echo "$cmd: maximum messages set to $max."
+[ "$verbose" ]&& echo "$cmd: connecting to $md."
+
+if [ "$proto" == "ssh" ] ;then
+	c=`ssh $md "sudo bash -c \"cd $maildir/cur;ls -lt\""|
+		sed -e '/^total/d'|
+		tee $tmp|wc -l`
+	[ $c -le $max ] && {
+		echo "$cmd: $mu has $c current messages only" >&2
 		exit 1
-	fi
-}
-[ -f $tmp ] && . $tmp
-
-case $port in
-	22) proto=ssh;;
-	143) proto=imap;;
-	993) proto=ssl;;
-	"") port=22;proto=ssh;[ "$verbose" ] && echo "$cmd: using port 22." >&2;;
-	*) echo "$cmd: proceedure for $port not known." >&2;exit;;
-esac
-
-# set defaults if nothing found
-addr=${addr:-"`id -nu`@`hostname -d`"}
-alert=${alert:-$addr}
-mbox=${mbox:-"INBOX"}
-srvr=${srvr:-"imap.`hostname -d`"}
-user=${user:-$addr}
-po=`echo $addr|awk -F@ '{split($2,a,".");print a[1]}'`
-proto=${proto:-"ssl"}
-warn=${warn:-100}
-
-if [ "$expunge" ];then
-	[ "$verbose" ] &&{
-		echo "$cmd: Warning messages in excess of $warn will be deleted"
 	}
+	f=`expr $max + 1`
+	[ "$verbose" ] &&{
+       		echo "$cmd: moving `expr $c - $max` messages for $mu."
+	}
+	cat $tmp|sed -ne ''$f',$p'|awk '{print $8}'|uniq|
+	while read yr;do
+		archive=$archf.$yr
+		ssh $md "sudo bash -c \"
+			[ -d $archf ] ||{
+				mkdir -m 700 $archf
+				chown -R popuser.popuser $archf
+			}
+			[ -d $archive ] ||{
+		       		mkdir -p -m 700 $archive/{cur,new,tmp}
+				touch $archive/maildirfolder
+				chmod 600 $archive/maildirfolder
+				chown -R popuser.popuser $archive
+			}\""
+	done
+	cat $tmp|sed -ne ''$f',$p'|
+	awk -v cmd=$cmd: -v v=$verbose '{
+		printf("ssh '$md' sudo mv '$maildir'/cur/"$9 " '$archf'."$8"/cur")|"sh";close("sh")
+		mvd[$8]++
+	}END{
+		if(v){
+			for (c in mvd){
+			   print(cmd,mvd[c],"messages moved to",c,"archive.")
+			}
+		}
+	}'
+	etot=`ssh $md "sudo find $maildir/cur -type f" |wc -l`
+	mtot=`expr $c - $etot`
 fi
-if [ "$list" ];then
-	expect -f $lst_mbxs $srvr $proto $addr $mbox "$passwd"|
-	awk '/^* LIST/{gsub(/"/,"",$5);print $5}'
-	exit
-fi
-
-
-#Check if host name resolves
-getent hosts $srvr >/dev/null||{
-	echo -e "${nl}$cmd: Can't find host \"$srvr\".">&2
-	exit 1
+[ "$verbose" ]&&{
+	echo "$cmd: $etot messages remain in $mu's current INBOX at $md."
 }
-
-[ "$mbox" == "$folders" ] && folders=""
-
-nc -zw 2 $srvr $port </dev/null || {
-       	echo -e "${nl}Port $port unavailable on $srvr ($user).">&2
-	exit 1
-}
-for n in "$folders" ;do
-	echo $folders|egrep -wq '.Archive' && archives=:
-done
-		
-if [ "$archives" ];then
-	ay=2012
-	while  [ $ay -lt  `date "+%Y"` ];do
-		afolders="$afolders INBOX.Archive.$ay"
-	       	ay=`expr $ay + 1`
-	done	
-	folders=`echo $folders|sed -e "s/\.Archive/$afolders/"` 
-fi
-for m in $mbox $folders ;do
-  	[ "$verbose" ] && echo -n "$cmd: Checking ${user}'s $m on $srvr: "
-	if [ $port -eq 22 ];then
-		mdomain=`echo $addr|awk -F@ '{print $2}'`
-		vuser=`echo $addr|awk -F@ '{print $1}'`
-		f=`echo $m|awk '{sub(/INBOX/,"");print}'`	
-		mdir=/var/qmail/mailnames/$mdomain/$vuser/Maildir/$f
-		total=`ssh $srvr "sudo find $mdir/{cur,new} -type f" 2>/dev/null|wc -l`
-	else
-  		suser=`echo $user|sed -ne 's/^\(.*\)@.*/\1/p'`
-		total=`expect -f $cnt_msgs $srvr $proto  $addr $m "$passwd"|\
-			awk '/EXISTS/{print $2}'`
-	fi
-	if [ -n "$total" ];then
-		if [ "$verbose" ]; then 
-			#printf "%6d\t$m\n" $total
-			echo  "$total messages"
-		elif [ ${total:-0} -ge $warn ];then
-			echo  "Warning: ${user}'s $m on $srvr has $total messages" >&2
-		fi
-	       	[ "$log" ] && {
-		  	logger -p mail.notice -t $cmd "$total messages for $user $m at $srvr."
-		}
-
-			
-		[ ${total:-0} -gt "$warn" -a "$notice" ] && {
-			fname=`echo $alert|awk -F@ '{split($1,a,".");print a[1]}'`
-			fname=`echo $fname|awk -F@ '{sub(".",substr((toupper($1)),1,1),$1);print}'`
-		
-			mailx -s "Your $mbox at $po" $alert <<- .
-				$fname
-
-			You have $total messages in your mail folder $m
-			at $po.
-		
-			Please delete or archive old messages.
-
-			If messages need to be kept on-line move them to
-			other folders.
-
-			Try to keep your inbox to under $warn messages.
-
-			Clifford W Fulford
-			Mail Administrator
-		.
-		}
-		if [ "$expunge" ];then
-		   del=`expr $total - $warn`
-		   expect -f $del_msgs $srvr $proto  $addr $m "$passwd" $del
-		   total=`expr $total - $del`
-		     [ "$log" ] &&{
-		       	logger -p mail.notice -t $cmd "$del messages deleted for $user $m at $srvr."
-		  	logger -p mail.notice -t $cmd "$total messages for $user $m at $srvr."
-		      }
-		      [ $verbose ] &&{
-		      	s=s;[ $del -eq 1 ] && s=""
-		      	echo "$cmd: $del message$s deleted for $user $m at $srvr."
-			echo "$cmd: $total message$s remaining for $user $m at $srvr."
-		      }
-		fi
-	else
-		[ "$verbose" ] && echo "$cmd: $user $mbx not found."
-		[ "$log" ] && {
-			logger -p mail.notice -t $cmd "$user $m at $srvr. Not found!"
-		}
-
-	fi
-done
-[ -f "$tmp" ] && rm $tmp
+[ "$log" ]&& logger -p mail.notice -t $cmd "$mtot messages archived for $ma at $co"
+[ "$log" ]&& logger -p mail.notice -t $cmd "$etot messages archived for $ma INBOX at $co"
+rm $tmp
